language: java

jdk:
- openjdk8
- openjdk11

# skip the Travis-CI install phase because Maven handles that directly
install:
- 'true'

script:
- "./mvnw verify -Pci -V -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"

